### ISSUE TITLE
1.13.6 Core Panic 

### ISSUE THREAD

**Issue by mcf-rocks** [pyth-network/pythnet#105]
```
Jun 18 18:11:55 midget pyth.sh[3723519]: [2023-06-18T17:11:55.056676544Z INFO  solana_runtime::accounts_db] remove_dead_slots_metadata: 1 dead slots
Jun 18 18:11:55 midget pyth.sh[3723519]: [2023-06-18T17:11:55.057058916Z WARN  solana_core::replay_stage] purging descendant: 76611703 with slot_id 542, of slot 76611703
Jun 18 18:11:55 midget pyth.sh[3723519]: [2023-06-18T17:11:55.057322793Z INFO  solana_ledger::blockstore] Pruning expired primary index 1 up to slot 76611703 (max requested: 76611704)
Jun 18 18:11:55 midget pyth.sh[3723519]: thread 'solReplayStage' panicked at 'We have tried to repair duplicate slot: 76611703 more than 10 times and are unable to freeze a block with bankhash 5X5rMSa6phgijsuC229dTrRXiH4WJN9j3SaAa1Qk9E2U, instead we have a block with bankhash Some(DjEsYGpGXNTJaC9os6xDo5g3vu7xaiCFTDkzMBcZHnyC). This is most likely a bug in the runtime. At this point manual intervention is needed to make progress. Exiting', core/src/replay_stage.rs:1252:25
Jun 18 18:11:55 midget pyth.sh[3723519]: stack backtrace:
Jun 18 18:11:55 midget pyth.sh[3723519]:    0: rust_begin_unwind
Jun 18 18:11:55 midget pyth.sh[3723519]:              at ./rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
Jun 18 18:11:55 midget pyth.sh[3723519]:    1: core::panicking::panic_fmt
Jun 18 18:11:55 midget pyth.sh[3723519]:              at ./rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
Jun 18 18:11:55 midget pyth.sh[3723519]:    2: hashbrown::map::HashMap<K,V,S,A>::retain
Jun 18 18:11:55 midget pyth.sh[3723519]:    3: solana_core::replay_stage::ReplayStage::dump_then_repair_correct_slots
Jun 18 18:11:55 midget pyth.sh[3723519]:    4: solana_core::replay_stage::ReplayStage::new::{{closure}}
Jun 18 18:11:55 midget pyth.sh[3723519]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Jun 18 18:11:55 midget pyth.sh[3723519]: [2023-06-18T17:11:55.069295371Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solReplayStage" one=1i message="panicked at 'We have tried to repair duplicate slot: 76611703 more than 10 times and are unable to freeze a block with bankhash 5X5rMSa6phgijsuC229dTrRXiH4WJN9j3SaAa1Qk9E2U, instead we have a block with bankhash Some(DjEsYGpGXNTJaC9os6xDo5g3vu7xaiCFTDkzMBcZHnyC). This is most likely a bug in the runtime. At this point manual intervention is needed to make progress. Exiting', core/src/replay_stage.rs:1252:25" location="core/src/replay_stage.rs:1252:25" version="1.15.0 (src:00000000; feat:1754009961, client:SolanaLabs)"
```

**Comment by mcf-rocks** [comment]
ignore me i'm stupid
